import { jsPDF } from "jspdf"
import { Project } from "@/types/project"

export const generateProjectPDF = (project: Project) => {
  const doc = new jsPDF()
  const primaryColor = [218, 124, 0] // Approximate orange from oklch(68.351% 0.19585 34.956)

  // Header
  doc.setFillColor(245, 240, 232) // Beige background
  doc.rect(0, 0, 210, 40, "F")
  
  doc.setFont("helvetica", "bold")
  doc.setFontSize(22)
  doc.setTextColor(30, 30, 30)
  doc.text(project.name.toUpperCase(), 15, 25)
  
  doc.setFontSize(10)
  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2])
  doc.text(project.status.toUpperCase(), 15, 32)
  
  doc.setTextColor(100, 100, 100)
  doc.text(project.address, 15, 37)

  let y = 50

  const addSection = (title: string) => {
    y += 10
    doc.setFont("helvetica", "bold")
    doc.setFontSize(14)
    doc.setTextColor(30, 30, 30)
    doc.text(title.toUpperCase(), 15, y)
    y += 2
    doc.setDrawColor(primaryColor[0], primaryColor[1], primaryColor[2])
    doc.setLineWidth(0.5)
    doc.line(15, y, 40, y)
    y += 10
  }

  const addRow = (label: string, value: any) => {
    doc.setFont("helvetica", "bold")
    doc.setFontSize(9)
    doc.setTextColor(120, 120, 120)
    doc.text(label.toUpperCase() + ":", 15, y)
    
    doc.setFont("helvetica", "normal")
    doc.setTextColor(30, 30, 30)
    doc.text(String(value || "N/A"), 60, y)
    y += 7
    
    if (y > 270) {
      doc.addPage()
      y = 20
    }
  }

  // Project Summary
  addSection("Project Summary")
  addRow("System Size", project.systemSize)
  addRow("System Type", project.systemType)
  addRow("PV Modules", project.pvModules)
  addRow("Inverters", project.inverters)
  addRow("Battery Backup", project.batteryBackup ? "Yes" : "No")
  addRow("Created At", new Date(project.createdAt).toLocaleDateString())

  // Customer Profile
  addSection("Customer Profile")
  addRow("Contact Name", project.user_profile?.contact_name)
  addRow("Company", project.user_profile?.company_name)
  addRow("Email", project.user_profile?.email)
  addRow("Phone", project.user_profile?.phone)

  // Site Details
  addSection("Site & Electrical")
  addRow("Roof Material", project.site_details?.roof_material)
  addRow("Roof Pitch", project.site_details?.roof_pitch)
  addRow("Arrays", project.site_details?.number_of_arrays)
  addRow("Utility", project.site_details?.utility_provider)
  addRow("Main Panel", project.electrical_details?.main_panel_size)
  addRow("Breaker", project.electrical_details?.main_breaker)

  // Equipment
  if (project.system_components && project.system_components.length > 0) {
    addSection("Equipment List")
    project.system_components.forEach((comp) => {
      addRow(`${comp.type} (${comp.qty})`, comp.make_model)
    })
  }

  // Footer
  const pageCount = doc.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFontSize(8)
    doc.setTextColor(150, 150, 150)
    doc.text(`Page ${i} of ${pageCount}`, 180, 285)
    doc.text("Generated by Antigravity Permit Systems", 15, 285)
  }

  doc.save(`${project.name}_Report.pdf`)
}
